// <auto-generated />
using FlightFuelConsumption.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FlightFuelConsumption.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180531184300_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightFuelConsumption.Infrastructure.Data.DataModel.AirportDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Airport");
                });

            modelBuilder.Entity("FlightFuelConsumption.Infrastructure.Data.DataModel.FlightDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DepartureAirportId");

                    b.Property<int?>("DestinationAirportId");

                    b.Property<double>("Distance");

                    b.Property<double>("FlightTime");

                    b.Property<double>("FuelConsumption");

                    b.Property<double>("TakeoffEffort");

                    b.HasKey("Id");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("DestinationAirportId");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("FlightFuelConsumption.Infrastructure.Data.DataModel.FlightDataModel", b =>
                {
                    b.HasOne("FlightFuelConsumption.Infrastructure.Data.DataModel.AirportDataModel", "DepartureAirport")
                        .WithMany("DepartureFlights")
                        .HasForeignKey("DepartureAirportId");

                    b.HasOne("FlightFuelConsumption.Infrastructure.Data.DataModel.AirportDataModel", "DestinationAirport")
                        .WithMany("DestinationFlights")
                        .HasForeignKey("DestinationAirportId");
                });
#pragma warning restore 612, 618
        }
    }
}
